Перевел на 1commands. Добавил удаление файла лога
oscript-library/tool1cd pull request #3
Opened 2017-11-27 08:44 UTC by Khorevaa

Очислил  вывод в консоль.
Сделал https://github.com/oscript-library/tool1cd/issues/2

2017-11-27 09:12 UTC, artbear requested changes
Есть небольшой вопрос

2017-11-27 09:12 UTC, artbear commented on table-reader.os
> +	Команда.ПоказыватьВыводНемедленно(Ложь);
А какое сейчас поведение у `ЗапуститьПриложение(СтрокаЗапуска, "", Истина, КодВозврата);` ?
вывод от команды выдается сразу или все-таки не сразу?

2017-11-27 09:12 UTC, artbear commented on table-reader.os
> +	Команда.ПоказыватьВыводНемедленно(Ложь);
Если сразу, то прятать лог через `Команда.ПоказыватьВыводНемедленно(Ложь);` не хорошо :(

что-то я не помню поведение `ЗапуститьПриложение` :( с 1коммандс уже все забыл.

2017-11-27 10:08 UTC, Khorevaa commented on table-reader.os
> +	Команда.ПоказыватьВыводНемедленно(Ложь);
Та делается вывод в файл лога. По мимо стандартного вывода..

2017-11-27 10:08 UTC, Khorevaa commented on table-reader.os
> +	Команда.ПоказыватьВыводНемедленно(Ложь);
@artbear Вывод да делается сразу..

2018-01-10 20:12 UTC, dmpas commented
@artbear @khorevaa я дико извиняюсь, а с этим ПР чего?

2018-01-10 20:15 UTC, artbear approved these changes

2018-01-10 20:16 UTC, merged